### ISSUE TITLE
Algumas magias não podem ser arrastadas para a ficha.

### ISSUE THREAD

**Issue by mclemente** [Kull4ck/tormenta20-compendium#10]
Vi que saiu atualização nova e fui tentar atualizar a ficha do Arcanista do meu grupo e deu a seguinte mensagem de erro no console para algumas magias:
```
Uncaught (in promise) TypeError: Cannot read property 'hasOwnProperty' of null
    at foundry.js:1368
    at Array.reduce (<anonymous>)
    at setProperty (foundry.js:1367)
    at Function.fromDropData (foundry.js:30318)
    at T20ActorSheet._onDropItem (foundry.js:16972)
    at T20ActorSheet._onDrop (foundry.js:16923)
    at DragDrop.callback (foundry.js:13495)
    at DragDrop._handleDrop (foundry.js:13546)
```
Então (1) criei um mundo do zero, (2) apenas com o Compêndio como módulo ativo. (3) Criei um personagem.
(4) Tentei puxar algumas magias (magias que falham: Luz, Primor Atlético, Resistência à Energia, Sopro das Uivantes)

Magias que funcionam sem problemas: Curar Ferimentos, Conjurar Monstro e Anular a Luz.

**Comment by TheTruePortal** [comment]
Já vi o problema (ele exige um identificar por conta dos aprimoramentos que antes não precisava). A correção está na fila para revisão e liberação.

**Comment by mclemente** [comment]
Agora está tudo certo. Muito obrigado.
