### ISSUE TITLE
Poderes de Inventor

### ISSUE THREAD

**Issue by Romrufus** [Kull4ck/tormenta20-compendium#17]
Olá,

Parabéns pelo ótimo trabalho, principalmente adicionando as informações da jornada heroica! Está incrível!

Mas vi que os poderes de inventor estão incompletos... Poderia verificar?

Sou novo no Foundry e no Github, mas se houver algo em que eu possa ajudar...

**Comment by Kull4ck** [comment]
Opa! Então sobre os poderes de inventor, eles não estão mais disponíveis no Compendium desde a v1.0 por ferirem o OGL da Jambo Editora, Infelizmente, esses poderes em específico, terão de ser feitos a mão pelos jogadores. Quando a Jambo Editora tiver alguma posição relacionada a isso e permitir o uso da classe inventor no Compendium, imediatamente irei lanchar um patch adicionando a classe.
