### ISSUE TITLE
Municao

### ISSUE THREAD

**Issue by eunaumtenhoid** [Kull4ck/tormenta20-compendium#8]
cara ta ficando muito TOP, mas aqui o pack de municao tu nao alterou a quantidade de municao continua 10, sobre  novos itens vc pretende colocar porcoes magicas, venenos e alguns itens especificos como os de origem e sobre o iten kit de oficio poderia tirar o <> pq com ele as tabelas nao funciona.

**Comment by TheTruePortal** [comment]
Cara, olhando o código parece normal.

Você está excluindo da ficha e incluindo de novo o equipamento? Porque o que já está na ficha não é alterado com a atualização do compedium. Veja também se não copiou o compedium localmente para seu jogo, porque nesse caso ele também não atualiza automaticamente.

**Comment by Kull4ck** [comment]
Boa tarde, eu tinha feito a alteração das munição, vou conferir de novo x.x
Sobre as poções, o problema é elas serem uma de cada magia existente, fica bem complicado. Mas vou verificar uma alternativa para isso. Vou ajustar o Kit de Oficio e mandar uma Att

**Comment by Kull4ck** [comment]
Subi uma correção de armas e itens para a v1.1, corrigindo as munições e alguns ícones, a principio tudo ok agora.

**Comment by eunaumtenhoid** [comment]
agora sim ta mostrando 20 na municao!
